version: '3.7'

services:
  server:
    entrypoint: [ "sh", "-c", "java -cp app:app/lib/* br.com.superatecnologia.managementapi.ManagementApiApplication" ]
    network_mode: "host"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_H2_CONSOLE_ENABLED=true
      - JWT_SECRET=V9Yct9ulyEKKLK9vt_HAcw
      - AWS_ACCESS_KEY=AKIASWDVHJ4IRIMH4COP
      - AWS_SECRET_KEY=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
      - EMAIL_FROM=filipe360@gmail.com
      - EMAIL_SUBJECT_OTP=Código OTP
      - EMAIL_SUBJECT_SIGNUP=Cadastro realizado com sucesso