spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driverClassName: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
  h2:
    console:
      enabled: ${SPRING_H2_CONSOLE_ENABLED}

cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}


email:
  from: ${EMAIL_FROM}
  subject:
    otp: ${EMAIL_SUBJECT_OTP}
    signup: ${EMAIL_SUBJECT_SIGNUP}

auth:
  util:
    jwt:
      secret: ${JWT_SECRET}