swagger:
  contact:
    name: 'Filipe Chiconello'
    email: "filipe360@gmail.com"
  app:
    name: Management API
    version: 0.1.0
    description: API responsible for management for accounts and transactions.
  base:
    package: br.com.superatecnologia.managementapi.controllers

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driverClassName: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
  h2:
    console:
      enabled: ${SPRING_H2_CONSOLE_ENABLED}

cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}


email:
  from: ${EMAIL_FROM}
  subject:
    otp: ${EMAIL_SUBJECT_OTP}
    signup: ${EMAIL_SUBJECT_SIGNUP}

auth:
  util:
    jwt:
      secret: ${JWT_SECRET}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path:
      path-mapping:
        health: /healthcheck